## IDS IPS (Time Series) Dataset 

-- SUMMARY 
SELECT
    LABEL,
    COUNT(*)                        AS ATK_COUNT,
    SUM(FLOW_DURATION)              AS TOTAL_FLOW,
    ROUND(SUM(PKT_SIZE_AVG),2)      AS PKT_SIZE,
    COUNT(DISTINCT DST_PORT)        AS PORTS_HIT,
    COUNT(DISTINCT PROTOCOL)        AS PROTOCOL_COUNT,
    LISTAGG(DISTINCT PROTOCOL,', ') WITHIN GROUP (ORDER BY PROTOCOL) AS PROTOCOL, 
    ROUND((MAX(TO_DATE(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS')) - MIN (TO_DATE(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS'))) * 24 * 60* 60, 2) AS DURATION_SEC
FROM
    IDS_1
GROUP BY
    LABEL
ORDER BY
    ATK_COUNT DESC, TOTAL_FLOW DESC
